### PR TITLE
Responsive filter

### LINKED ISSUE #37: Change Grocery Logo because of bad code
REMOVE THE CODE and change it with new img

button
-------REMOVE ALL CODE INSIDE THIS-------
/button

### LINKED ISSUE #44: Responsive Filter Bar

### PR DESCRIPTION
**Pull request by yellowberard**
closes #44 
closes #37

### CODE REVIEW

**Comment by yellowberard** [comment]
image

**Comment by yellowberard** [comment]
image

**Comment by yellowberard** [comment]
image

**Review by mrkc2303 — APPROVED** [review]
Good Work

**Pull request merged**
