### PR TITLE
Added Header

### LINKED ISSUE #1: Header Code and Design
Issue 1

Making of Header in the website

DEADLINE - 10 September 2021

### PR DESCRIPTION
**Pull request by mrkc2303**
Added Header and minor changes in Footer

Fix #1

### CODE REVIEW

**Comment by mrkc2303** [comment]
image

**Comment by yellowberard** [comment]
i will add my review tomorrow

**Comment by yellowberard** [comment]
why the logo in footer not visible in the screenshot?

**Comment by mrkc2303** [comment]
Has some error loading the video. Have a 50% chance of loading making the website slow.
Will work on it and solve it later

**Comment by mrkc2303** [comment]
Solved the issue!!
Removed the video, and added the gif

**Comment by mrkc2303** [comment]
image

**Review by yellowberard — APPROVED** [review]

**Pull request merged**
