### PR TITLE
Category changes

### PR DESCRIPTION
**Pull request by KushagraJain58-cmd**

### CODE REVIEW

**Comment by KushagraJain58-cmd** [comment]
image

**Review by yellowberard — CHANGES_REQUESTED** [review]
remove class ai au d7 ds

**Review by mrkc2303 — CHANGES_REQUESTED** [review]
Unnecessary classes has been added kindly remove it

**Comment by mrkc2303** [comment]
Does this pr needed anymore @KushagraJain58-cmd 
Or different from the next pr which is merged?

**Pull request closed without merging**
